### ISSUE TITLE
server-sent events how to with routing-controllers?

### ISSUE THREAD

**Issue by xmlking** [typestack/routing-controllers#117]
exploring ways to add to server-sent events(SSE) to `routing-controllers` based project. 
 Following code works with simple `koa`. 
 looking for help on how I can use `PassThrough` stream with `routing-controllers` 

```js
const Koa = require('koa');
const Router = require('koa-router');
var bodyParser = require('koa-bodyparser');
const events = require('events');
const cors  = require('kcors');

const PassThrough = require('stream').PassThrough;
const dispatcher = new events.EventEmitter();
const app = new Koa();
const router = new Router();

router.post('/send', bodyParser(), async (ctx) => {
  console.log('body', ctx.request.body);
  dispatcher.emit('message', ctx.request.body);
  ctx.response.set('Content-Type', 'text/plain;charset=utf-8');
  ctx.body = 'ok';
});

router.get('/subscribe', async (ctx) => {
  let stream = new PassThrough();

  let fn = (data, event) => {
    if(event) stream.write(`event: ${event}\n`);
    stream.write(`data: ${JSON.stringify(data)}\n\n`);
  }
  let finish = (e) => dispatcher.removeListener('message', fn);


  ctx.response.status = 200;
  ctx.response.type = 'text/event-stream;charset=utf-8';
  ctx.response.set('Cache-Control', 'no-cache');
  ctx.body = stream;

  stream.write(': open stream\n\n');
  dispatcher.on('message', fn);
  // ctx.req.on('close', ctx.res.end());
  ctx.req.on('close', finish);
  ctx.req.on('finish', finish);
  ctx.req.on('error', finish);
});

app
  .use(cors())
  .use(router.routes())
  .use(router.allowedMethods())
  .listen(process.env.PORT || 3001, process.env.IP || '0.0.0.0');
```

```html
<html>
<head>
  <script>
    var source = new EventSource("http://localhost:3001/subscribe");
    source.addEventListener('message', function(e) {
      console.log('data', JSON.parse(e.data).aaa)
      if(JSON.parse(e.data).aaa === 0) {
        console.log('closing')
        source.close()
      }
    }, false);

    source.addEventListener('open', function(e) {
      console.log('Connection was opened.', e)
    }, false);

    source.addEventListener('error', function(e) {
      if (e.readyState === EventSource.CLOSED) {
        console.log('Connection was closed.');
      }
    }, false);

  </script>
</head>
<body>

</body>
</html>
```

**Comment by xmlking** [comment]
Got some success with following code , except   for `request.on`.  
```
    // request.on('close', finish);
    // request.on('finish', finish);
    // request.on('error', finish);
```

**Working Code**
```ts
import {Service} from 'typedi';
import {Request, Response} from 'koa';
import {Controller, Param, Body, Get, Post, Put, Delete, JsonController, Req, Res} from 'routing-controllers';
import * as events from 'events';

const PassThrough = require('stream').PassThrough;
const dispatcher = new events.EventEmitter();

@Service()
@JsonController()
export class StreamController {

  @Post('/stream/send')
  post(@Body() data: any) {
    console.log('data', data);
    dispatcher.emit('message', data);
    return {result: 'ok'};
  }

  @Get('/stream')
  async stream(@Req() request: any, @Res() response: Response) {
    response.status = 200;
    response.type = 'text/event-stream; charset=utf-8';
    response.set('Cache-Control', 'no-cache');

    const stream = new PassThrough();

    const fn = (data, event) => {
      if (event) {
        stream.write(`event: ${event}\n`);
      }
      stream.write(`data: ${JSON.stringify(data)}\n\n`);
    }
    const finish = (e) => dispatcher.removeListener('message', fn);

    response.body = stream;

    stream.write(': open stream\n\n');
    dispatcher.on('message', fn); 
    // request.on('close', finish);
    // request.on('finish', finish);
    // request.on('error', finish);
  }
}
```

**Comment by pleerock** [comment]
I don't see what exact problem with routing-controllers. Can you provide a simplified example what is working as expected with express/koa and don't work with routing-controllers?

**Comment by xmlking** [comment]
in the HTML client about,  when client receives data  ` { aaa: 0 }` ,  I am clousing EventSource on the client side. this triggers execution of ` request.on('close', finish);`  code on server-side and below  exception thrown.

**Problem:** with is the correct way to call ` request.on` in  `routing-controllers` environment? 
when using koa without `routing-controllers`,  this works `ctx.req.on('close', finish);`
 
```ts
  @Get('/stream')
  async stream(@Req() request: any, @Res() response: Response) {
    try {
      response.status = 200;
      response.type = 'text/event-stream; charset=utf-8';
      response.set('Cache-Control', 'no-cache');

      const stream = new PassThrough();

      const fn = (data, event) => {
        if (event) {
          stream.write(`event: ${event}\n`);
        }
        stream.write(`data: ${JSON.stringify(data)}\n\n`);
      }
      const finish = (e) => dispatcher.removeListener('message', fn);

      response.body = stream;

      stream.write(': open stream\n\n');

      dispatcher.on('message', fn);
      request.on('close', finish);
      request.on('finish', finish);
      request.on('error', finish);
    } catch (e) {
      console.log(e)
    }
  }
```
error:
```
listening on port 3000
TypeError: request.on is not a function
    at StreamController.<anonymous> (/server/src/controllers/StreamController.ts:54:15)
    at Generator.next (<anonymous>)
    at /server/src/controllers/StreamController.ts:19:71
    at __awaiter (/server/src/controllers/StreamController.ts:15:12)
    at StreamController.stream (/server/src/controllers/StreamController.ts:64:16)
    at ActionMetadata.executeAction (/server/src/metadata/ActionMetadata.ts:250:62)
    at /server/src/RoutingControllerExecutor.ts:92:35
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
GET /api/stream - 0ms
data { aaa: 10 }
POST /api/stream/send - 0ms
data { aaa: 0 }
POST /api/stream/send - 0ms
```

**Comment by xmlking** [comment]
Ok. I am testing below  modified   code.
somehow the `finish` callback function never called :(
**Expected :** when browser's **EventSource**  client closes,  server-side `finish` callback function should be called. 
 
```ts
import {Service} from 'typedi';
import {Request, Response} from 'koa';
import {Controller, Param, Body, Get, Post, Put, Delete, JsonController, Req, Res} from 'routing-controllers';
import * as events from 'events';

const PassThrough = require('stream').PassThrough;
const dispatcher = new events.EventEmitter();

@Service()
@JsonController()
export class StreamController {

  @Post('/stream/send')
  post(@Body() data: any) {
    console.log('data', data);
    dispatcher.emit('message', data);
    return {result: 'ok'};
  }

  @Get('/stream')
  async stream(@Req() request: Request, @Res() response: Response) {
    try {
      response.status = 200;
      response.type = 'text/event-stream; charset=utf-8';
      response.set('Cache-Control', 'no-cache');

      const stream = new PassThrough();

      const fn = (data, event) => {
        if (event) {
          stream.write(`event: ${event}\n`);
        }
        stream.write(`data: ${JSON.stringify(data)}\n\n`);
      }
      const finish = (e) => {
        console.log('finish...')
        dispatcher.removeListener('message', fn);
      }

      response.body = stream;

      stream.write(': open stream\n\n');

      dispatcher.on('message', fn);
      request.req.on('close', finish);
      request.req.on('finish', finish);
      request.req.on('error', finish);
    } catch (e) {
      console.log(e)
    }
  }
}

// ES https://localhost:3000/api/stream
// POST https://localhost:3000/api/stream/send 
// Payload : {"aaa": 10} or {"aaa": 0}
```

**Comment by pleerock** [comment]
`@Req() request` gives you object from `context.request`, so `@Req() request` === `context.request`, thats why you should not have problems with request. I see you are using `context.req` in your examples, not `context.request`, why? are you using koa v2?

**Comment by xmlking** [comment]
where do you see I am using `context.req`?  yes I am using Koa 2.0 for both cases. 
I have two examples here: 
1. Pure Koa 2.0 example shown here: [stream.js](https://github.com/xmlking/hub/blob/master/server/src/stream.js), [stream.html](https://github.com/xmlking/hub/blob/master/server/src/stream.html). In this example, I am not using `routing-controllers` . This is working perfectly as expected. 
2. [StreamController.ts](https://github.com/xmlking/hub/blob/master/server/src/controllers/StreamController.ts) Implemented with `routing-controllers` and Koa 2.0 .  In this case : `.on('close', finish),.on('finish', finish);.on('error', finish);` are not working. 

if your question is,  in Case2, why I am using `request.req.on('close', finish);` instead of `request.on('close', finish);` , I got error ` request.on is not a function` with `request.on('close', finish);`.

you can reproduce error easily with code provided in the links. steps to reproduce  :
1. start the server `yarn run start`
2. open client app i.e., `stream.html`
3. post below json payload to  https://localhost:3000/api/send/message via postman
   payload:  `{"aaa": 10}`    should print `10` in browser console. 
   payload:  `{"aaa": 0}`    should print `closing` in browser console.   'finish...' should be printed on  the server-side   **(which is not happening)**

**Comment by pleerock** [comment]
>where do you see I am using context.req?

from your code example in first post
```ts
  ctx.req.on('close', finish);
  ctx.req.on('finish', finish);
  ctx.req.on('error', finish);
});
```

`@Req() request` provides you a [Koa Request object](https://github.com/koajs/koa/blob/master/docs/api/context.md#ctxrequest), same if you do `context.request`. Looks like you need node request object, not koa. Also I didn't find in koa docs what is request.req, [there is no such method in the docs.](https://github.com/koajs/koa/blob/master/docs/api/request.md)

**Comment by xmlking** [comment]
In first example, I am **not** using `@Req() request` it is pure Koa 2.0 code based on [koa sample here](https://github.com/koajs/koa/issues/543).  we don't need to worry on it as it is working 100% as expected. 
I think the Koa `Request` is a wrapper to `node request` object. To get raw `node request` object we have to use `ctx.req`. I am concluding this base on [this](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L625)

My requirement is when using `@JsonController()/@Req()`,  I need to get access to raw `node request` which implement `stream.Readable` which in turn extends `EventEmitter`. So  `raw node request`  has `.on()` method.

**Comment by pleerock** [comment]
I don't really understand xmlking requirements, @19majkel94 can you please help with this issue.

**Comment by 19majkel94** [comment]
I don't know what is the problem. @xmlking Are you sure that `ctx.request.req` is exactly the same as `ctx.req`?
If you need `ctx` instead of `request`, just use `@Ctx()`:
```ts
async stream(@Ctx() ctx: Context) {}
```

**Comment by OysteinAmundsen** [comment]
I would also like to get this to work. 

Consider the following two pieces of code. First one works, second does not. Yet their contents are identical, the only difference is that the first one is setup as a middleware directly to expressJS, the second is instantiated by routing-controllers as a JsonController.

So far my deduction is that when the Response object is processed through routing-controllers, it is ultimately being terminated by calling res.end(), which is bad for a long-lived connection. When I run the first piece of code, the response is wrapped properly in the stream object, and lives on. However, I do need to continuously hammer my `keepAlive` method, otherwise my stream dies after between 30 seconds to 2 minutes time. 

**services/SSEController instantiated manually from my express server setup**

```
import { Server } from '../';
import { Container, Service } from 'typedi';

import { Express, Request, Response } from 'express';
import { EventEmitter } from 'events';
import { PassThrough } from 'stream';

import { Logger } from '../utils/Logger';
const dispatcher = new EventEmitter();

/**
 * Singleton class serving as SSE event handler
 */
@Service()
export class SSEController {
  app: Express;

  constructor() {
    this.app = Container.get(Server).app; // My ExpressJS app object

    // Register the route this middleware should respond to
    this.app.use('/api/event', (req, res) => this.connect(req, res));

    // Register this class with the TypeDI engine, so we can hook up to the `publish` method here from 
    // other places in our application.
    Container.set(SSEController, this);
  }

  /**
   * A Client connects and the response object is configured as a
   * long-lived connection
   *
   * @param req
   * @param res
   */
  public connect(req: Request, res: Response): void {
    req.socket.setTimeout(Number.MAX_VALUE);

    // Create the event stream
    const stream = new PassThrough();
    stream.pipe(res);

    // A handler function called each time something is to be published to our clients
    const handler = (data: any, event: any) => {
      if (event) {
        Logger.log.debug(`SSE Event received: ${event}`);
        stream.write(`event: ${event}\n`);
      }
      Logger.log.debug(`SSE Data published: ${JSON.stringify(data)}`);
      stream.write(`data: ${JSON.stringify(data)}\n\n`);
    }

    // Register the handler on our dispatcher
    dispatcher.on('message', handler);
    Logger.log.debug(`Client #${dispatcher.listenerCount('message')} connected!`);

    // The 'close' event is fired when a user closes their browser window.
    // Remove this client from our openConnections pool
    req.on('close', (err?: any) => this.closeConnection(handler, err));
    req.on('finish', (err?: any) => this.closeConnection(handler, err));
    req.on('error', (err?: any) => this.closeConnection(handler, err));

    // Return the response via our stream
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive'
    });
    stream.write(': open stream\n\n');
    this.keepAlive(stream);
  }

  /**
   * If we do not write to this stream once every variable 30sek - 2 minute intervals,
   * this connection will be terminated.
   *
   * @param stream the stream to keep alive
   */
  private keepAlive(stream: PassThrough) {
    setTimeout(() => {
      try {
        stream.write('\n');
        this.keepAlive(stream);
      } catch (ex) {
        Logger.log.debug(ex);
        this.closeConnection(stream);
      }
    }, 30 * 1000);
  }

  /**
   * Close the connection to one client
   * This is usually called as an event handler for one of three event states on the
   * request object: `close`, `finish` or `error`
   *
   * @param handler The client handler to close
   * @param err optionally an error object if the stream closes through an exception
   */
  private closeConnection(handler: any, err?: any) {
    if (err) { Logger.log.error(err); }

    Logger.log.debug(`SSE Client #${dispatcher.listenerCount('message')} disconnecting!`);
    dispatcher.removeListener('message', handler);
  }

  /**
   * Server publishing an event
   *
   * @param message any string. Can be a stringified JSON object
   */
  public publish(message: string) {
    Logger.log.debug(`SSE Publishing ${message} to ${dispatcher.listenerCount('message')} clients!`);
    dispatcher.emit('message', message);
    return {result: 'ok'};
  }
}
```

**controllers/SSEController**

```
import {Container, Service} from 'typedi';
import {Param, Body, Get, Post, JsonController, Req, Res} from 'routing-controllers';
import {Request, Response} from 'express';
import {EventEmitter} from 'events';
import {PassThrough} from 'stream';

import { Logger } from '../utils/Logger';

const dispatcher = new EventEmitter();

@Service()
@JsonController()
export class SSEController {
  openConnections: Response[] = [];

  /**
   * A Client connects and the response object is configured as a
   * long-lived connection
   *
   * @param req
   * @param res
   */
  @Get('/event')
  async connect(@Req() req: Request, @Res() res: Response) {
    req.socket.setTimeout(Number.MAX_VALUE);

    // Create the event stream
    const stream = new PassThrough();
    stream.pipe(res);

    // A handler function called each time something is to be published to our clients
    const handler = (data: any, event: any) => {
      if (event) {
        Logger.log.debug(`SSE Event received: ${event}`);
        stream.write(`event: ${event}\n`);
      }
      Logger.log.debug(`SSE Data published: ${JSON.stringify(data)}`);
      stream.write(`data: ${JSON.stringify(data)}\n\n`);
    }

    // Register the handler on our dispatcher
    dispatcher.on('message', handler);
    Logger.log.debug(`Client #${dispatcher.listenerCount('message')} connected!`);

    // The 'close' event is fired when a user closes their browser window.
    // Remove this client from our openConnections pool
    req.on('close', (err?: any) => this.closeConnection(handler, err));
    req.on('finish', (err?: any) => this.closeConnection(handler, err));
    req.on('error', (err?: any) => this.closeConnection(handler, err));

    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive'
    });
    stream.write(': open stream\n\n');
    this.keepAlive(stream);
  }

  /**
   * If we do not write to this stream once every variable 30sek - 2 minute intervals,
   * this connection will be terminated.
   *
   * @param stream the stream to keep alive
   */
  private keepAlive(stream: PassThrough) {
    setTimeout(() => {
      try {
        stream.write('\n');
        this.keepAlive(stream);
      } catch (ex) {
        Logger.log.debug(ex);
        this.closeConnection(stream);
      }
    }, 30 * 1000);
  }

  /**
   * Close the connection to one client
   * This is usually called as an event handler for one of three event states on the
   * request object: `close`, `finish` or `error`
   *
   * @param handler The client handler to close
   * @param err optionally an error object if the stream closes through an exception
   */
  private closeConnection(handler: any, err?: any) {
    if (err) { Logger.log.error(err); }

    Logger.log.debug(`SSE Client #${dispatcher.listenerCount('message')} disconnecting!`);
    dispatcher.removeListener('message', handler);
  }

  /**
   * Server publishing an event
   *
   * @param message any string. Can be a stringified JSON object
   */
  @Post('/event')
  public publish(message: string) {
    Logger.log.debug(`SSE Publishing ${message} to ${dispatcher.listenerCount('message')} clients!`);
    dispatcher.emit('message', message);
    return {result: 'ok'};
  }
}
```

**Comment by 19majkel94** [comment]
So, looks like we go to the conclusion - it wasn't problem with calling `req.on`, but:

> So far my deduction is that when the Response object is processed through routing-controllers, it is ultimately being terminated by routing-controllers calling res.end(), which is bad for a long-lived connection.

Yes, this is an issue, I have some problems with streaming files. @pleerock if think we need to introduce a decorator to mark the method as routing-controller shouldn't handle the response, dev did this my himself. Or we can do breaking change and assume that when we inject `res` object, the response has been handled and we should handle response when the returned value from action method is undefined.

**Comment by pleerock** [comment]
@19majkel94 i didnt worked with streams in express, can you provide a short example of code that reproduce the issue and reason why it causes this issue. And what do you mean by "shouldn't handle the response" ? Do you mean we should not call `.send` method?

**Comment by 19majkel94** [comment]
Yes, for streaming we have to manually send headers and body, so when we finish using express api, we return undefined from action handler and routing-contollers is trying to send 404 response but it can't because of headers already sent.

But when someone don't return the promise but use callback api, he may have problem - first the undefined will be returned by action, then the response 404 send and then his callback called which would try to send headers/body manually using express api, which will fail.

**Comment by pleerock** [comment]
Okay, so problem is here:
```ts

                if (action.isJsonTyped) {
                    options.response.json();
                } else {
                    options.response.send();
                }
                options.next();
```

Okay I think I understood the problem and looks like  a better solution is to create a new decorator.

**Comment by 19majkel94** [comment]
So let's find a name - `@ManualResponse`? 😆

**Comment by pleerock** [comment]
Sounds rude... And does not really explain things, we need something more descriptive like `@PreventContentSend` but more easy and elegant...

**Comment by 19majkel94** [comment]
Or maybe as an option to `@Res` decorator?  Like `@Res({ preventContentSend: true })`?
Disabling automatic response is tightly coupled to the `@Res`, for koa it would be `@Ctx`.

**Comment by pleerock** [comment]
No, too implicit. Decorator is better.

**Comment by fabiob** [comment]
One possible way to 'detect' that an user wants to handle the response by him/herself is returning the response itself from the action. I've used this approach before, when I wrote a small "routing-controllers" myself (before I knew about this project).

So we can just test if the action result `===` the response object.

The action can be written as:

```typescript
@Get("/users/direct")
getUsersDirectExpress(@Res() response: any): any {
  return response.status(201).contentType("custom/x-sample").send("hi, I was written directly to the response");
}
```

**Comment by fabiob** [comment]
I've updated my PR #286 to include my proposal.

**Comment by pleerock** [comment]
What is resolution on this issue? Can it be closed now?

**Comment by 19majkel94** [comment]
I'm not sure, if 0.7.3 is released, we can ask @xmlking to check if the issue still exist when he return the response/ctx object.

**Comment by pleerock** [comment]
Yes its released
