### ISSUE TITLE
HttpError no running

### ISSUE THREAD

**Issue by brunorafaeI** [typestack/routing-controllers#346]
I have this issue in my HttpError:

{"name":"NotFoundError","stack":"Error\n    at NotFoundError.HttpError [as constructor] (C:\\Users\\bruno\\Desktop\\DEV\\node-pgsql\\node_modules\\routing-controllers\\http-error\\HttpError.js:27:23)\n    at new NotFoundError (C:\\Users\\bruno\\Desktop\\DEV\\node-pgsql\\node_modules\\routing-controllers\\http-error\\NotFoundError.js:20:28)\n    at ExpressDriver.handleSuccess (C:\\Users\\bruno\\Desktop\\DEV\\node-pgsql\\node_modules\\routing-controllers\\driver\\express\\ExpressDriver.js:289:23)\n    at C:\\Users\\bruno\\Desktop\\DEV\\node-pgsql\\node_modules\\routing-controllers\\RoutingControllers.js:128:61\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}

Can someone help me?

````
import { Param, NotFoundError } from "routing-controllers";
...
@Get("/users/:id")
	getOne(@Param("id") id: number) {
	    const user = this.userRepository.findOneById(id);
	    if (!user) throw new NotFoundError("User was not found"); 
	    return user;
	}
...

**Comment by 19majkel94** [comment]
Please describe in more details what is the problem here 😉

**Comment by brunorafaeI** [comment]
I'm developing a REST API on nodejs + express + pgsql using (TypeScript), when I try to treat the error messages as shown in the examples, it does'nt return the error message in which I specify, everything works perfectly is only when it searches for an ID that does'nt exist in the database and instead of showing me the error message that I put in the function it returns me this huge message, I can't customize the message, I tried several examples! do you can help me?

**Comment by NoNameProvided** [comment]
Hi @brunorafaeI! 

I cannot reproduce your issue. Here is my code sample: 

```ts
import "reflect-metadata";
import { createExpressServer, JsonController, Get, NotFoundError } from "routing-controllers";

@JsonController()
export class RouteController {

  @Get("")
  getAll() {
    throw new NotFoundError('User was not found');
  }
}

const app = createExpressServer({
  controllers: [RouteController]
});

app.listen(3000);
```

After running this, and opening `localhost:3000` I see the following error message, and this is the expected behavior.

```
{
  "name": "NotFoundError",
  "message": "User was not found",
  "stack": "Error\n    at NotFoundError.HttpError [as constructor] (\/Users\/attila\/projects\/rc-346\/node_modules\/routing-controllers\/http-error\/HttpError.js:27:23)\n    at new NotFoundError (\/Users\/attila\/projects\/rc-346\/node_modules\/routing-controllers\/http-error\/NotFoundError.js:20:28)\n    at RouteController.getAll (\/Users\/attila\/projects\/rc-346\/build\/app.js:16:15)\n    at ActionMetadata.callMethod (\/Users\/attila\/projects\/rc-346\/node_modules\/routing-controllers\/metadata\/ActionMetadata.js:108:48)\n    at \/Users\/attila\/projects\/rc-346\/node_modules\/routing-controllers\/RoutingControllers.js:92:140\n    at <anonymous>\n    at process._tickCallback (internal\/process\/next_tick.js:188:7)"
}
```

**Comment by iamanthos** [comment]
@HttpCode(201)
    @Post('/createList')
    public CreateList(@Body() req: any,@Res() res: Response){
        try{
        let response: any;
        const db = MongoHelper.client.db('CRUD');
         const insertedOutput: Promise<any> =
         db.collection('weapon').insertMany(req);

        insertedOutput.then(resolvedPromise => {
            if(resolvedPromise.result.ok == 1){
               response =  {
                    'statusCode' : '200',
                    'count' : resolvedPromise.insertedCount,
                    'id' : resolvedPromise.insertedId
                }

                console.log('Response ' + JSON.stringify(response));
                res.send(200).json(response);
            }
        })
        .catch(error => {
            console.log(error);
        });


Hi The above code is causing to throw the error.
Please find the logs.


Error:
    at NotFoundError.HttpError [as constructor] (E:\DevSpace\src\http-error\HttpError.ts:19:22)
    at new NotFoundError (E:\DevSpace\src\http-error\NotFoundError.ts:10:9)
    at ExpressDriver.handleSuccess (E:\DevSpace\src\driver\express\ExpressDriver.ts:314:23)
    at E:\DevSpace\src\RoutingControllers.ts:161:45
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
Response {"statusCode":"200","count":1}
express deprecated res.send(status): Use res.sendStatus(status) instead src\controller\crudController.ts:53:25
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (E:\DevSpace\NodeMongoTypescript\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (E:\DevSpace\NodeMongoTypescript\node_modules\express\lib\response.js:170:12)
    at CreateList.insertedOutput.then.resolvedPromise (E:\DevSpace\NodeMongoTypescript\src\controller\crudController.ts:47:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by iamrocky316** [comment]
> @httpcode(201)
> @post('/createList')
> public CreateList(@Body() req: any,@res() res: Response){
> try{
> let response: any;
> const db = MongoHelper.client.db('CRUD');
> const insertedOutput: Promise =
> db.collection('weapon').insertMany(req);
> 
> ```
>     insertedOutput.then(resolvedPromise => {
>         if(resolvedPromise.result.ok == 1){
>            response =  {
>                 'statusCode' : '200',
>                 'count' : resolvedPromise.insertedCount,
>                 'id' : resolvedPromise.insertedId
>             }
> 
>             console.log('Response ' + JSON.stringify(response));
>             res.send(200).json(response);
>         }
>     })
>     .catch(error => {
>         console.log(error);
>     });
> ```
> 
> Hi The above code is causing to throw the error.
> Please find the logs.
> 
> Error:
> at NotFoundError.HttpError [as constructor] (E:\DevSpace\src\http-error\HttpError.ts:19:22)
> at new NotFoundError (E:\DevSpace\src\http-error\NotFoundError.ts:10:9)
> at ExpressDriver.handleSuccess (E:\DevSpace\src\driver\express\ExpressDriver.ts:314:23)
> at E:\DevSpace\src\RoutingControllers.ts:161:45
> at
> at process._tickDomainCallback (internal/process/next_tick.js:229:7)
> Response {"statusCode":"200","count":1}
> express deprecated res.send(status): Use res.sendStatus(status) instead src\controller\crudController.ts:53:25
> Error: Can't set headers after they are sent.
> at validateHeader (_http_outgoing.js:491:11)
> at ServerResponse.setHeader (_http_outgoing.js:498:3)
> at ServerResponse.header (E:\DevSpace\NodeMongoTypescript\node_modules\express\lib\response.js:771:10)
> at ServerResponse.send (E:\DevSpace\NodeMongoTypescript\node_modules\express\lib\response.js:170:12)
> at CreateList.insertedOutput.then.resolvedPromise (E:\DevSpace\NodeMongoTypescript\src\controller\crudController.ts:47:21)
> at
> at process._tickDomainCallback (internal/process/next_tick.js:229:7)

Why does the error stack show in src "**E:\DevSpace\src\http-error\HttpError.ts:19:22**". Shouldn't the error be thrown inside the node_modules since that is where the file exists? I am confused. Please help me

**Comment by NoNameProvided** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
