### ISSUE TITLE
@Param only accepts numbers

### ISSUE THREAD

**Issue by buzzyboy** [typestack/routing-controllers#347]
I'm trying to use a route like this:   @Delete('/account/:apiKey')

The apiKeys are strings and not numbers. If I try to hit the endpoint with a string I get a bad request (500) error:

Error
at ParameterParseJsonError.HttpError [as constructor] (/myProjectDirectory/src/http-error/HttpError.ts:19:22)
at ParameterParseJsonError.BadRequestError [as constructor] (/myProjectDirectory/src/http-error/BadRequestError.ts:10:9)
at new ParameterParseJsonError (/myProjectDirectory/src/error/ParameterParseJsonError.ts:10:9)
at ActionParameterHandler.parseValue (/myProjectDirectory/src/ActionParameterHandler.ts:153:23)
at ActionParameterHandler.normalizeParamValue (/myProjectDirectory/src/ActionParameterHandler.ts:137:34)
at ActionParameterHandler.handle (/myProjectDirectory/src/ActionParameterHandler.ts:44:28)
at /myProjectDirectory/src/RoutingControllers.ts:116:49
at Array.map (<anonymous>)
at RoutingControllers.executeAction (/myProjectDirectory/src/RoutingControllers.ts:116:14)
at /myProjectDirectory/src/RoutingControllers.ts:83:33

If I use a number, I get my own defined 404 custom error as expected.

**Comment by buzzyboy** [comment]
Wait, I realized that it can actually work with "string" but not "String".
I changed it from: 
  deleteAccount(@Res() response: any, @Param("apiKey") apiKey: String) {
to:
  deleteAccount(@Res() response: any, @Param("apiKey") apiKey: string) {

and it worked.

**Comment by 19majkel94** [comment]
It's weird but I'm glad you figured out how to fix it 😉

**Comment by NoNameProvided** [comment]
Hi @buzzyboy!

This issue happened because the `String` type matches strings created via the `String` constructor, aka `new String('your-api-key')`. You should never set any Typescript type to `String`, `Number` or `Boolean`. It's considered a bad pratice and listed in the[ official "Typescript Dont's" list](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html). You always should use the lower-case variants.
