### ISSUE TITLE
how to use graphql-koa-server through routing-controllers 

### ISSUE THREAD

**Issue by JimmyDaddy** [typestack/routing-controllers#361]
There is my code
```typescript
import { graphiqlKoa, graphqlKoa } from 'apollo-server-koa';
import { GraphQLSchema } from 'graphql';
import { Context } from 'koa';
// import { Context } from 'koa';
import { Controller, Ctx, Get, Post } from 'routing-controllers';
import { loadSchema } from '../graphql';

@Controller('')
export default class GraphqlController {
  schema: GraphQLSchema;
  constructor() {
    this.schema = loadSchema();
  }

  @Get('/graphql')
  @Post('/graphql')
  async graphql(@Ctx() ctx: Context, next: () => {}) {
    await graphqlKoa({
      schema: this.schema,
    })(ctx, next);
  }

  @Post('/graphiql')
  @Get('/graphiql')
  async graphiql(@Ctx() ctx: Context) {
    await graphiqlKoa({
      endpointURL: '/graphql',
    })(ctx);
  }
}
```
it throws error 
```
Error at NotFoundError.HttpError [as constructor] (/Users/jimmydaddy/study/sxc/rgb-ts/node_modules/routing-controllers/http-error/HttpError.js:27:23) at new NotFoundError (/Users/jimmydaddy/study/sxc/rgb-ts/node_modules/routing-controllers/http-error/NotFoundError.js:20:28) at KoaDriver.handleSuccess (/Users/jimmydaddy/study/sxc/rgb-ts/node_modules/routing-controllers/driver/koa/KoaDriver.js:269:23) at /Users/jimmydaddy/study/sxc/rgb-ts/node_modules/routing-controllers/RoutingControllers.js:128:61 at at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by JimmyDaddy** [comment]
I'm sorry I know how to fix this problem

by the code below
```
import { graphiqlKoa, graphqlKoa } from 'apollo-server-koa';
import { GraphQLSchema } from 'graphql';
import { Context } from 'koa';
// import { Context } from 'koa';
import { Controller, Ctx, Get, Post } from 'routing-controllers';
import { loadSchema } from '../graphql';

@Controller('')
export default class GraphqlController {
  schema: GraphQLSchema;
  constructor() {
    this.schema = loadSchema();
  }

  @Get('/graphql')
  @Post('/graphql')
  async graphql(@Ctx() ctx: Context, next: () => {}) {
    await graphqlKoa({
      schema: this.schema,
    })(ctx, next);
    return ctx;
  }

  @Post('/graphiql')
  @Get('/graphiql')
  async graphiql(@Ctx() ctx: Context) {
    await graphiqlKoa({
      endpointURL: '/graphql',
    })(ctx);
    return ctx;
  }
}
```
just return the `Context`

**Comment by marcelowa** [comment]
Apparently this method no longer works with the new apollo-server-koa 2
