### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vtrphan** [typestack/routing-controllers#377]
already solved

**Comment by bodyslam** [comment]
I'm seeing this error in my application.

Version of routing-controllers
```
{
  "name": "routing-controllers",
  "private": false,
  "version": "0.7.7",
...
```

Error message:
```
2018-08-09T21:31:29.066Z [-] error [da48130922f0280] {"message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded
    at Array.find (native)
    at MetadataStorage.findMetadata (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/metadata/MetadataStorage.js:126:44)
    at MetadataStorage.findExposeMetadata (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/metadata/MetadataStorage.js:55:21)
    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:282:75
    at Array.filter (<anonymous>)
    at TransformOperationExecutor.getKeys (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:281:29)
    at TransformOperationExecutor.transform (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:79:29)
    at _loop_1 (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:154:45)
    at TransformOperationExecutor.transform (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:178:17)
    at _loop_1 (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:154:45)"} [{"name":"serviceLogger","hostname":"HEN008713","pid":14148,"level":50,"logLevel":50,"stack":"RangeError: Maximum call stack size exceeded
    at Array.find (native)
    at MetadataStorage.findMetadata (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/metadata/MetadataStorage.js:126:44)
    at MetadataStorage.findExposeMetadata (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/metadata/MetadataStorage.js:55:21)
    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:282:75
    at Array.filter (<anonymous>)
    at TransformOperationExecutor.getKeys (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:281:29)
    at TransformOperationExecutor.transform (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:79:29)
    at _loop_1 (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:154:45)
    at TransformOperationExecutor.transform (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:178:17)
    at _loop_1 (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:154:45)","v":0}]
```

My usage:
```
import { Get, JsonController, Param } from 'be-nj-foundation';
import { getAll, getOne } from '../models/SessionCartModel';

interface IResponseObject {
  msg: string
}

@JsonController()
export class SessionCartController {

  @Get('/')
  public welcome(): IResponseObject {
    return { msg: 'Hello from session_carts' };
  }

  @Get('/session_carts')
  public async getAllCarts(): Promise<AWS.DynamoDB.GetItemOutput> {
    console.log('Start getAll()');
    return await getAll(); // <--- Error occurs here; this is a JSON object fetched from DynamoDB
  }

  @Get('/session_carts/:id')
  public async getOne(@Param('id') id: string): Promise<AWS.DynamoDB.GetItemOutput> {
    return await getOne(id);
  }
}
```

Any help would be greatly appreciated.

**Comment by omerkhan8** [comment]
> already solved

how did you solved this?

**Comment by NoNameProvided** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
