### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bodyslam** [typestack/routing-controllers#427]
I'm seeing this error in my application.

Version of routing-controllers
```
{
  "name": "routing-controllers",
  "private": false,
  "version": "0.7.7",
...
```

Error message:
```
2018-08-09T21:31:29.066Z [-] error [da48130922f0280] {"message":"Maximum call stack size exceeded","stack":"RangeError: Maximum call stack size exceeded
    at Array.find (native)
    at MetadataStorage.findMetadata (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/metadata/MetadataStorage.js:126:44)
    at MetadataStorage.findExposeMetadata (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/metadata/MetadataStorage.js:55:21)
    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:282:75
    at Array.filter (<anonymous>)
    at TransformOperationExecutor.getKeys (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:281:29)
    at TransformOperationExecutor.transform (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:79:29)
    at _loop_1 (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:154:45)
    at TransformOperationExecutor.transform (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:178:17)
    at _loop_1 (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:154:45)"} [{"name":"serviceLogger","hostname":"HEN008713","pid":14148,"level":50,"logLevel":50,"stack":"RangeError: Maximum call stack size exceeded
    at Array.find (native)
    at MetadataStorage.findMetadata (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/metadata/MetadataStorage.js:126:44)
    at MetadataStorage.findExposeMetadata (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/metadata/MetadataStorage.js:55:21)
    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:282:75
    at Array.filter (<anonymous>)
    at TransformOperationExecutor.getKeys (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:281:29)
    at TransformOperationExecutor.transform (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:79:29)
    at _loop_1 (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:154:45)
    at TransformOperationExecutor.transform (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:178:17)
    at _loop_1 (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/class-transformer/TransformOperationExecutor.js:154:45)","v":0}]
```

My usage:
```
import { Get, JsonController, Param } from 'be-nj-foundation';
import { getAll, getOne } from '../models/SessionCartModel';

interface IResponseObject {
  msg: string
}

@JsonController()
export class SessionCartController {

  @Get('/')
  public welcome(): IResponseObject {
    return { msg: 'Hello from session_carts' };
  }

  @Get('/session_carts')
  public async getAllCarts(): Promise<AWS.DynamoDB.GetItemOutput> {
    console.log('Start getAll()');
    return await getAll(); // <--- Error occurs here; this is a JSON object fetched from DynamoDB
  }

  @Get('/session_carts/:id')
  public async getOne(@Param('id') id: string): Promise<AWS.DynamoDB.GetItemOutput> {
    return await getOne(id);
  }
}
```

Any help would be greatly appreciated.

**Comment by bodyslam** [comment]
Upon further investigation a more useful error popped up

```
2018-08-10T16:20:25.928Z [-] error [934a526e4817180] {"message":"","stack":"Error\n    at NotFoundError.HttpError [as constructor] (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new NotFoundError (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/routing-controllers/http-error/NotFoundError.js:20:28)\n    at ExpressDriver.handleSuccess (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/routing-controllers/driver/express/ExpressDriver.js:289:23)\n    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/routing-controllers/RoutingControllers.js:128:61\n    at propagateAslWrapper (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/async-listener/index.js:502:23)\n    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/async-listener/glue.js:188:31\n    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/async-listener/index.js:539:70\n    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/async-listener/glue.js:188:31\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)"} [{"name":"serviceLogger","hostname":"HEN008713","pid":38614,"level":50,"logLevel":50,"stack":"Error\n    at NotFoundError.HttpError [as constructor] (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new NotFoundError (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/routing-controllers/http-error/NotFoundError.js:20:28)\n    at ExpressDriver.handleSuccess (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/routing-controllers/driver/express/ExpressDriver.js:289:23)\n    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/routing-controllers/RoutingControllers.js:128:61\n    at propagateAslWrapper (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/async-listener/index.js:502:23)\n    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/async-listener/glue.js:188:31\n    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/async-listener/index.js:539:70\n    at /Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/async-listener/glue.js:188:31\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)","v":0}]
(node:38614) UnhandledPromiseRejectionWarning: Fatal! RangeError: Maximum call stack size exceeded
(node:38614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38614) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:38614) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at Promise.then (<anonymous>)
    at Promise.wrappedThen (/Users/thwong/repo/be-nj-service-cart-sessioncart/node_modules/async-listener/index.js:522:27)
    at insertSessionCart (/Users/thwong/repo/be-nj-service-cart-sessioncart/dist/tools/misc/Cart.js:17:33)
    at insertSessionCart (/Users/thwong/repo/be-nj-service-cart-sessioncart/dist/tools/misc/Cart.js:17:9)
    at insertSessionCart (/Users/thwong/repo/be-nj-service-cart-sessioncart/dist/tools/misc/Cart.js:17:9)
    at insertSessionCart (/Users/thwong/repo/be-nj-service-cart-sessioncart/dist/tools/misc/Cart.js:17:9)
    at insertSessionCart (/Users/thwong/repo/be-nj-service-cart-sessioncart/dist/tools/misc/Cart.js:17:9)
    at insertSessionCart (/Users/thwong/repo/be-nj-service-cart-sessioncart/dist/tools/misc/Cart.js:17:9)
    at insertSessionCart (/Users/thwong/repo/be-nj-service-cart-sessioncart/dist/tools/misc/Cart.js:17:9)
    at insertSessionCart (/Users/thwong/repo/be-nj-service-cart-sessioncart/dist/tools/misc/Cart.js:17:9)
(node:38614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
I found the uncaught exception and the issue went away.  Hope this helps someone else and sorry to bug you guys.

**Comment by mjcc007** [comment]
how do you resolve the problem? thanks!

**Comment by bodyslam** [comment]
@mjcc007 Its been a while since I looked at this issue but if I recall all I did was wrap the external service call with a try catch.

```@Get('/session_carts')
  public async getAllCarts(): Promise<AWS.DynamoDB.GetItemOutput> {
    try {
      return await getAll();  
    } catch(e) {
      // Handle the error here
    }
 }
```

Hope that helps
