### ISSUE TITLE
authorizationChecker throws an error 

### ISSUE THREAD

**Issue by filipcro** [typestack/routing-controllers#433]
I have written two helper functions for authorization, which use JWT. Also I have put `@Authorized() `before route which require it. Here are my functions. 

```
import { Action } from "routing-controllers";

import { getConnection } from "typeorm";
import { verify, decode } from 'jsonwebtoken';

import { User } from "../entity/User";

export const currentUserChecker = async (action: Action) => {
    try {
        const token = action.request.headers["authorization"];     
        const decodedToken =  (decode(token));
        const id = (decodedToken as {id: number}).id;
        return await getConnection().getRepository(User).findOne(id);
    } catch(err) {
        return false;
    }
}

export const authorizationChecker = (action: Action, roles: string[]) => {
    try {
        const token = action.request.headers["authorization"];
        verify(token, process.env.JWT_SECRET);
    } catch(err) {
        return false;
    }
    return true;
}
```

But if request comes with invalid token, error will be displayed in console. Valid JWT works fine. How to solve this? Here is the error.

```
Error
    at AuthorizationRequiredError.HttpError [as constructor] (/home/filip/Projects/V-AltServer/src/http-error/HttpError.ts:19:22)
    at AuthorizationRequiredError.UnauthorizedError [as constructor] (/home/filip/Projects/V-AltServer/src/http-error/UnauthorizedError.ts:10:9)
    at new AuthorizationRequiredError (/home/filip/Projects/V-AltServer/src/error/AuthorizationRequiredError.ts:12:9)
    at handleError_1 (/home/filip/Projects/V-AltServer/src/driver/express/ExpressDriver.ts:111:87)
    at /home/filip/Projects/V-AltServer/src/driver/express/ExpressDriver.ts:123:25
    at Layer.handle [as handle_request] (/home/filip/Projects/V-AltServer/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/filip/Projects/V-AltServer/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/filip/Projects/V-AltServer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/filip/Projects/V-AltServer/node_modules/express/lib/router/layer.js:95:5)
    at /home/filip/Projects/V-AltServer/node_modules/express/lib/router/index.js:281:22
```

**Comment by Eraledm** [comment]
I got a similar error, returning true results in a valid response but when returning false it doesn't send anything back to clients, just the console log

**Comment by NoNameProvided** [comment]
Locking this as out of date. If anyone experiences the same problem please open a new issue.
