### ISSUE TITLE
Returning 204 empty response causes "Cannot set headers after they are sent to the client" error

### ISSUE THREAD

**Issue by jakubbialas** [typestack/routing-controllers#482]
I'm trying to return 204 empty response like this:
```typescript
    @Get('/')
    @OnUndefined(204)
    get() {
        return;
    }
```
Or like this:
```typescript
    @Get('/')
    get() {
        return null;
    }
```
Both examples should work as explained here: https://github.com/typestack/routing-controllers#controlling-empty-responses

And it returns 204 empty response, but expressjs throws uncatched exception:
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:482:11)
    at ServerResponse.header (/media/sdb2/jbialas/Projects/ng/node-api/node_modules/express/lib/response.js:767:10)
    at ServerResponse.json (/media/sdb2/jbialas/Projects/ng/node-api/node_modules/express/lib/response.js:264:10)
    at ExpressDriver.handleSuccess (/media/sdb2/jbialas/Projects/ng/node-api/node_modules/routing-controllers/driver/express/ExpressDriver.js:281:38)
    at /media/sdb2/jbialas/Projects/ng/node-api/node_modules/routing-controllers/RoutingControllers.js:128:61
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

**Comment by jakubbialas** [comment]
Nevermind, my mistake..

I somehow managed to register same controller twice, so the action was called twice, and second call have to fail as headers were indeed already sent.
