### ISSUE TITLE
ERR_HTTP_HEADERS_SENT on XML response

### ISSUE THREAD

**Issue by SiroDiaz** [typestack/routing-controllers#513]
```typescript
import sitemap from '../../config/sitemap';

@Controller()
export default class IndexController {

  @Get('/sitemap.xml')
  @Header('Content-Type', 'application/xml')
  public getSitemap() {
    return sitemap.toXML();
  }
}
```

I get the following error when send a string and want to apply a header. There is no XmlController decorator?

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at applyHeaders (C:\Users\siroc\projects\cloouder\node_modules\cors\lib\index.js:153:15)
    at applyHeaders (C:\Users\siroc\projects\cloouder\node_modules\cors\lib\index.js:149:11)
    at applyHeaders (C:\Users\siroc\projects\cloouder\node_modules\cors\lib\index.js:149:11)
    at cors (C:\Users\siroc\projects\cloouder\node_modules\cors\lib\index.js:187:7)
    at C:\Users\siroc\projects\cloouder\node_modules\cors\lib\index.js:224:17
    at originCallback (C:\Users\siroc\projects\cloouder\node_modules\cors\lib\index.js:214:15)
    at C:\Users\siroc\projects\cloouder\node_modules\cors\lib\index.js:219:13
    at optionsCallback (C:\Users\siroc\projects\cloouder\node_modules\cors\lib\index.js:199:9)
    at corsMiddleware (C:\Users\siroc\projects\cloouder\node_modules\cors\lib\index.js:204:7)
    at Layer.handle [as handle_request] (C:\Users\siroc\projects\cloouder\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\siroc\projects\cloouder\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\siroc\projects\cloouder\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\siroc\projects\cloouder\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\siroc\projects\cloouder\node_modules\express\lib\router\index.js:275:10)
    at Object.next (C:\Users\siroc\projects\cloouder\node_modules\express\lib\router\route.js:127:14)
```

**Comment by elthrasher** [comment]
Hi @SiroDiaz , I'm able to return an xml body with that header and I don't get the error. Are you able to provide a sample repo that shows the bug? BTW, I just put this in one of the sample apps included in this repo:
```
    @Get("/xml")
    @Header("Content-Type", "application/xml")
    getXml() {
      return "<blarg>blah</blarg>";
    }
```

**Comment by SiroDiaz** [comment]
Hi @elthrasher, it seems that is an error with Next.JS 9.x. Nextjs sends a header with each request. I isolated the route @Get('/sitemap.xml') in an empty test project and it works fine. So it should be an integration error with Nextjs.

**Comment by elthrasher** [comment]
You are serving up nextjs via routing-controllers? I'm certain that's not something which is explicitly supported. I don't know a lot about nextjs. Care to share your setup?

**Comment by SiroDiaz** [comment]
Nextjs is been served using plain get route methods but for the API i'm using routing-controllers. Sorry, but i can share a little bit of the setup.
All dependecies up to date in package.json except routing-controllers.
**package.json**

- routing-controllers@^0.7.7
- express@^4.17.1
- next@^9.0.7
- sitemap@^4.1.1

**application entrypoint (index.ts)**

```typescript
import * as express from 'express';
import { Request, Response } from 'express';
import * as next from 'next';
import 'reflect-metadata';
require('dotenv').config();

import server from './api';
import sitemap from './config/sitemap';

const dev = process.env.NODE_ENV !== 'production';

const app = next({ dev });
const handle = app.getRequestHandler();

Promise.all([app.prepare(), server()])
  .then(async (values) => {
    const [, apiServer] = values;
    
    apiServer.addHandler('get', '/sitemap.xml', (req: Request, res: Response) => {
      try {
        const xml = sitemap.toXML();
        res.setHeader('Content-Type', 'application/xml');
        return res.send(xml);
      } catch (e) {
        console.error(e);
        res.status(500).end();
      }
    });

    apiServer.addHandler('get', '/w', async (req: Request, res: Response) => {
      return app.render(req, res, '/w', { v: req.query.v, consent: req.cookies.p_consent });
    });

    apiServer.addHandler('get', '/v/:id', async (req: Request, res: Response) => {
      return app.render(req, res, '/v', { id: req.params.id, consent: req.cookies.p_consent });
    });

    apiServer.addHandler('get', '*', async (req: express.Request, res: express.Response) => {
      return handle(req, res);
    });

    apiServer.listenAndServe();
  })
  .catch((error) => {
    console.log(error);
    process.exit(1);
  });

```

In the Application.ts class, in constructor part:

```typescript
this.application = express();
this.registerGlobalMiddlewares();

useExpressServer(this.application, {
  routePrefix: '/api',
  cors: true,
  controllers: [
    path.join(__dirname, 'controllers', '*.ts'),
    path.join(__dirname, 'controllers', '*.js')
  ]
});

this.application.use(Sentry.Handlers.errorHandler());
```

using in index.ts this piece of code manually it get fixed:

```typescript
apiServer.addHandler('get', '/sitemap.xml', (req: Request, res: Response) => {
      try {
        const xml = sitemap.toXML();
        res.setHeader('Content-Type', 'application/xml');
        return res.send(xml);
      } catch (e) {
        console.error(e);
        res.status(500).end();
      }
});
```
