### ISSUE TITLE
decorator not working with supertest

### ISSUE THREAD

**Issue by JHyeok** [typestack/routing-controllers#540]
when running supertest, the binding of the routes do not occur when using useExpressServer which lead to a 404 from a jest test.

```
    expected 200 "OK", got 404 "Not Found"

      at Test.Object.<anonymous>.Test._assertStatus (node_modules/supertest/lib/test.js:268:12)
      at Test.Object.<anonymous>.Test._assertFunction (node_modules/supertest/lib/test.js:283:11)
      at Test.Object.<anonymous>.Test.assert (node_modules/supertest/lib/test.js:173:18)
      at Server.localAssert (node_modules/supertest/lib/test.js:131:12)

(node:22812) UnhandledPromiseRejectionWarning: TypeError: PlatformTools_1.PlatformTools.load(...).sync is not a function
(node:22812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 1)
(node:22812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The other test framework is the same error as above.
I want to solve it using routing-controller.
maybe probable that the decorator is being ignored.

Note: that it works well for unit tests.

**Comment by jgdodson** [comment]
I'm getting this error too (`TypeError: PlatformTools_1.PlatformTools.load(...).sync`), and this issue it literally the only other place on the internet where I can find that string of text. Any idea what the PlatformTools is about?

**Comment by JHyeok** [comment]
@jgdodson 
I solved this problem.
https://github.com/JHyeok/jaebook-server/blob/master/test/e2e/api/users.test.ts
The solution is in beforeAll, after All and utils in the test folder.

**Comment by NoNameProvided** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
