### ISSUE TITLE
authorizationChecker throw Error: at AuthorizationRequiredError.HttpError [as constructor]

### ISSUE THREAD

**Issue by zecka** [typestack/routing-controllers#559]
I try to implement an authorizationChecker, but it throw the following error when it return false

```
Error: at AuthorizationRequiredError.HttpError [as constructor] (/src/http-error/HttpError.ts:19:22) at AuthorizationRequiredError.UnauthorizedError [as constructor] (/src/http-error/UnauthorizedError.ts:10:9) at new AuthorizationRequiredError (/src/error/AuthorizationRequiredError.ts:12:9) at handleError_1 (/src/driver/express/ExpressDriver.ts:111:87) at /src/driver/express/ExpressDriver.ts:120:45 at process._tickCallback (internal/process/next_tick.js:68:7)
```

I reproduce this bug with minimal configuration:

```typescript
// index.ts
import "reflect-metadata";
import { createExpressServer, Action } from "routing-controllers";
import { DemoController } from "./controllers/DemoController";

createExpressServer({
  controllers: [DemoController],
  authorizationChecker: async (action: Action, roles: string[]) => {
    return false;
  }
}).listen(3000);
```

```typescript
// controllers/DemoController.ts
import { Controller, Get, Authorized } from "routing-controllers";
@Controller("/")
export class DemoController {
  @Authorized()
  @Get("/")
  getDemo() {
    return { demo: "this is a demo" };
  }
}
```
Here is a codesandbox with this issue: https://codesandbox.io/s/routing-controllers-bug-ovdwt?file=/src/index.ts

What am I doing wrong ?

**Comment by jotamorais** [comment]
@zecka, the `authorizationCheck` will return a boolean. If you return `false` (like in your example) and not handle the exception anywhere else, that's the exception you will get and that's the expected behavior - it's telling there's an authorization error.

You can turn the `defaultErrorHandler` off if you want to handle those exceptions yourself.

**Comment by zecka** [comment]
Thank's @jotamorais for your answer. But I don't know how to handle the exception.

My goal is to return an Unauthorized error to the client with a 401 status page if the verification fail in authorizationChecker like that:
`{"httpCode":401,"name":"UnauthorizedError","message":"Your are not allowed"}`

**Comment by jotamorais** [comment]
@zecka, routing-controllers will do that out-of-the-box for you. If you handle the messages in a central place, you disable the `defaultErrorHandler` and configure a specific middleware for error handling, that way, any of the built-ins exceptions such as

- `HttpError`
- `BadRequestError`
- `ForbiddenError`
- `InternalServerError`
- `MethodNotAllowedError`
- `NotAcceptableError`
- `NotFoundError`
- `UnauthorizedError`

will always output the format you want:

**`index.ts`**
```typescript
import "reflect-metadata";
import {
  createExpressServer,
  Action,
  UnauthorizedError
} from "routing-controllers";
import { DemoController } from "./controllers/DemoController";
import { ErrorHandler } from "./middlewares/ErrorHandler";

createExpressServer({
  development: false,
  defaultErrorHandler: false,
  middlewares: [ErrorHandler],
  controllers: [DemoController],
  authorizationChecker: async (action: Action, roles: string[]) => {
    throw new UnauthorizedError("You're not authorized");
    // return false;
  }
}).listen(3000);
````

**`middlewares/ErrorHandler.ts`**
```typescript
import {
  Middleware,
  ExpressErrorMiddlewareInterface
} from "routing-controllers";

@Middleware({ type: "after" })
export class ErrorHandler implements ExpressErrorMiddlewareInterface {
  public error(
    error: any,
    request: any,
    response: any,
    next: (err: any) => any
  ) {
    if (response.headersSent) {
      return;
    }

    response.json(error);
  }
}
```

**`controllers/DemoController.ts`**
```typescript
import { Controller, Get, Authorized } from "routing-controllers";
@Controller("/")
export class DemoController {
  @Authorized()
  @Get("/")
  getDemo() {
    return { demo: "this is a demo" };
  }
}

```

Will automatically produce something like:

```json
{"httpCode":401,"name":"UnauthorizedError","message":"You're not authorized"}
```

**Comment by zecka** [comment]
Thank you very much for your precise answer, it's much clearer to me now. That's exactly what I was trying to do.

**Comment by jotamorais** [comment]
> Thank you very much for your precise answer, it's much clearer to me now. That's exactly what I was trying to do.
> How can I buy a coffee for you ?

:rofl: 
Glad to help. No need to buy a coffee - your feedback for improvements or PRs will pay many times more :)

**Comment by NoNameProvided** [comment]
This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
