### ISSUE TITLE
@UploadedFile example

### ISSUE THREAD

**Issue by gb53smith** [typestack/routing-controllers#598]
I am using this code:
```
   @Post("/recipe/import")
   @Render("multer")
   saveFile(@UploadedFile("import_name") file: Express.Multer.File) {
      console.log(file)
      let msg = "hello"
      let file2 = "there"

      return {
         msg: msg,
         file: file2
      }
```
But get the error:
```
POST /recipe/import
MulterError: Unexpected field
    at wrappedFileFilter (X:\TypeScript\Recipes\node_modules\multer\index.js:40:19)
    at Busboy.<anonymous> (X:\TypeScript\Recipes\node_modules\multer\lib\make-middleware.js:114:7)
    at Busboy.emit (events.js:314:20)
    at Busboy.emit (X:\TypeScript\Recipes\node_modules\busboy\lib\main.js:38:33)
    at PartStream.<anonymous> (X:\TypeScript\Recipes\node_modules\busboy\lib\types\multipart.js:213:13)
    at PartStream.emit (events.js:314:20)
    at HeaderParser.<anonymous> (X:\TypeScript\Recipes\node_modules\dicer\lib\Dicer.js:51:16)
    at HeaderParser.emit (events.js:314:20)
    at HeaderParser._finish (X:\TypeScript\Recipes\node_modules\dicer\lib\HeaderParser.js:68:8)
    at SBMH.<anonymous> (X:\TypeScript\Recipes\node_modules\dicer\lib\HeaderParser.js:40:12)
```
Also getting errors with this fileUploadOptions at fileFilter and limits.
```
   export const fileUploadOptions = () => {
        multer.diskStorage({
            destination: (req: any, file: any, cb: any) => {
                destination: './uploads/'
            },
            filename: (req: any, file: any, cb: any) => {
                cb(null, file.fieldname + path.extname(file.originalname));
            },
        }),
        fileFilter: (req: any, file: any, cb: any) => { checkFileType(file, cb)
        },
        limits: {
            fieldNameSize: 255,
            fileSize: 1024 * 1024 * 2
        }

    }
```

Is there a simple example of @UploadedFile decorator in this repository?

**Comment by MarkMurphy** [comment]
Your `fileUploadOptions` doesn't return anything and you're not passing it to the decorator in your example. I believe there is a simple example in the docs: https://github.com/typestack/routing-controllers#inject-uploaded-file. 

Although the example there looks incorrect as well, it's missing parentheses around the braces.

**Comment by gb53smith** [comment]
I am missing storage:  in front of multer.diskStorage{... but Vscode doesn't like fileFilter and limits that follows.
New to typescript but I think that
= () => means: this is a function that returns the following...  In this case a json record.
How would you correct the example in the documentation?
I get the unexpected field error even without the use of fileUploadOptions.
Meanwhile, I have got the app.post(... method working as per the Multer documentation.
It would be nice to have all the routes defined in routing-controllers.

**Comment by RW-DiefBell** [comment]
Some examples I did on my other account:
https://github.com/MerrickKing/Express-Typescript-Boilerplate/blob/Multipart-File-Upload/src/config/uploads.cfg.ts
https://github.com/MerrickKing/Express-Typescript-Boilerplate/blob/Multipart-File-Upload/src/api/controllers/upload.ctrl.ts

**Comment by gb53smith** [comment]
Thank you RW-DiefBell for you example.   The method used to create uploadOpts compiles without errors.
Unfortunately, something else is wrong since I get exactly the same error message as in the original post.
ie about MulterError: Unexpected field
The route /upload get works. The  route /upload post creates tmp/uploads directory and the error message.
Perhaps a new compatibility issuse?  Here are my dependencies:
```
 "devDependencies": {
      "@types/body-parser": "^1.19.0",
      "@types/express": "^4.17.6",
      "@types/jquery": "^3.5.0",
      "@types/multer": "^1.4.3",
      "@types/node": "^8.0.29",
      "typescript": "3.3.3333"
   },
   "dependencies": {
      "body-parser": "^1.18.1",
      "class-transformer": "^0.2.3",
      "class-validator": "^0.12.2",
      "express": "^4.15.4",
      "multer": "^1.4.2",
      "pug": "^3.0.0",
      "reflect-metadata": "^0.1.13",
      "routing-controllers": "^0.9.0-alpha.4",
      "sqlite3": "^4.2.0",
      "typeorm": "^0.2.25"
   },
```

**Comment by gb53smith** [comment]
I had to modify the RW-DiefBell example for a single upload file.   You must use UploadedFile instead of UploadedFiles.  The UploadedFile argument must match name='import' in the the HTML form.  (import for example)
I have included this working code below:

```
import { Request } from "express-serve-static-core";
import { diskStorage } from "multer";
import { extname } from "path";

type Callback = (error : null | Error, val : any) => void;
type File = Express.Multer.File;

export namespace uploads
{
    export const options = {
        storage: diskStorage({
            destination: "tmp/uploads"
        }),
        fileFilter: (req : Request, file : File, cb : Callback) =>
        {
            const isValid = file.mimetype == "text/html" && extname(file.originalname) == ".html";
            console.log(`Uploaded file with mime type ${file.mimetype} is ${isValid ? "valid" : "invalid"}.`);
            cb(null, isValid);
        },
        limits: {
        }
    };
}

import { UploadedFile } from "routing-controllers";
import { uploads } from "../multer";
import { readFileSync } from "fs";
import { join } from "path";
const uploadOpts = uploads.options;

...

@Controller("/upload")
export class UploadController
{
    @Get("/")
    private uploadPage()
    {
        return readFileSync(join(__dirname, "../views/index.html"));
    }

    @Post("/")
    private handleUpload(@UploadedFile("import", { options: uploadOpts } ) files : File[])
    
    {
      console.log("Handle Upload")
        return `${files.length} files uploaded!`;
    }
}
```
