### ISSUE TITLE
sendFile errors

### ISSUE THREAD

**Issue by gb53smith** [typestack/routing-controllers#630]
Trying to serve a static html file.  I have reviewed posts with a search for sendFile but with no luck resolving the issue.

My Code:

```@JsonController("/static")
export class StaticController {

   @Get("/schmiing")
   @UseBefore(checkJwt)
   private async schmiing(@Req() request: any, @Res() response: Response) {
      const fileName = path.resolve(__dirname, "../static/", "PrivateBookWebSite.html");
      console.log(fileName)
      
      response.sendFile(fileName)
     //console.log(response)
      return response
   }
}
```
Results:
Output Error Message
Cannot GET /static/schmiing

If console.log(response) is added I also get
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (X:\TypeScript\PrivateBook\node_modules\send\index.js:390:13)
    at SendStream.send (X:\TypeScript\PrivateBook\node_modules\send\index.js:617:10)
    at onstat (X:\TypeScript\PrivateBook\node_modules\send\index.js:729:10)
    at FSReqCallback.oncomplete (fs.js:177:5)

I also tried this:
```
  try {
         await new Promise<void>((resolve, reject) => {
            response.sendFile(fileName, (err: any) => {
               if (err) reject(err);
               resolve();
            });
         });
      } catch (error) {
         console.log(error);
         throw new Error(error);
      }

      return;
```

I get the html file served but with these warning messages.  

```
(node:7624) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:536:11)
    at ServerResponse.header (X:\TypeScript\PrivateBook\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (X:\TypeScript\PrivateBook\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (X:\TypeScript\PrivateBook\node_modules\express\lib\response.js:267:15)
    at ExpressDriver.handleError (X:\TypeScript\PrivateBook\node_modules\routing-controllers\driver\express\ExpressDriver.js:369:28)       
    at X:\TypeScript\PrivateBook\node_modules\routing-controllers\RoutingControllers.js:104:33
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7624) UnhandledPromiseRejectionWarning: Unhandled promise rejection. 
This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection, 
use the CLI flag `--unhandled-rejections=strict` 
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7624) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. 
In the future, promise rejections that are not handled will terminate the Node.js process 
with a non-zero exit code.
```

I have successfully rendered pages using PUG.  I am surprised that sending static pages is more difficult. 😊

**Comment by gb53smith** [comment]
I worked out this one line solution:
```
 return  await new Promise<Response>(() => {response.sendFile(fileName, () => {})});
```
Basically waits for the sendFile response with no error checking.  
No warning messages were reported in the nodejs log.

I will leave this issue open for perhaps better solutions.

**Comment by attilaorosz** [comment]
Closing in favor of #611
