### ISSUE TITLE
fix: TypeError: Reflect.getMetadata is not a function

### ISSUE THREAD

**Issue by balza** [typestack/routing-controllers#669]
### Description
I'm a javascript newbie, I set up a sample application
+
- app.ts
- UserController.ts

copied from the project homepage following the instruction

when I run 

`npm run start`

I get the following exception:

> node dist/app.js

```
/home/balza/workspace/devops/prova/node_modules/routing-controllers/cjs/metadata/ParamMetadata.js:36
            const ParamTypes = Reflect.getMetadata('design:paramtypes', args.object, args.method);
                                       ^

TypeError: Reflect.getMetadata is not a function
    at new ParamMetadata (/home/balza/workspace/devops/prova/node_modules/routing-controllers/cjs/metadata/ParamMetadata.js:36:40)
    at index_1.getMetadataArgsStorage.filterParamsWithTargetAndMethod.map.paramArgs (/home/balza/workspace/devops/prova/node_modules/routing-controllers/cjs/metadata-builder/MetadataBuilder.js:111:31)
    at Array.map (<anonymous>)
    at MetadataBuilder.createParams (/home/balza/workspace/devops/prova/node_modules/routing-controllers/cjs/metadata-builder/MetadataBuilder.js:111:14)
    at actionsWithTarget.map.actionArgs (/home/balza/workspace/devops/prova/node_modules/routing-controllers/cjs/metadata-builder/MetadataBuilder.js:98:34)
    at Array.map (<anonymous>)
    at MetadataBuilder.createActions (/home/balza/workspace/devops/prova/node_modules/routing-controllers/cjs/metadata-builder/MetadataBuilder.js:95:34)
    at controllers.map.controllerArgs (/home/balza/workspace/devops/prova/node_modules/routing-controllers/cjs/metadata-builder/MetadataBuilder.js:75:39)
    at Array.map (<anonymous>)
    at MetadataBuilder.createControllers (/home/balza/workspace/devops/prova/node_modules/routing-controllers/cjs/metadata-builder/MetadataBuilder.js:71:28)
```
the configuration looks ok

Thank you

**Comment by alexisvisco** [comment]
add `import "reflect-metadata"` in you main :)

**Comment by balza** [comment]
uh! ... thank you
