### ISSUE TITLE
fix: Cannot read property 'prototype' of undefined (QueryParams parsing simple case)

### ISSUE THREAD

**Issue by alexisvisco** [typestack/routing-controllers#675]
### Description
The query params is not parsed, not validated, and throws an error. In the documentation a simple case like that should, must woks. 

**Minimal code-snippet showcasing the problem**

```ts
import { Get, JsonController, QueryParams, createKoaServer } from 'routing-controllers'
import { IsAlpha, IsUUID } from 'class-validator'
import "reflect-metadata"


export class GetAllUsersInput {
  @IsAlpha()
  name: string

  @IsUUID('4')
  id: string
}

@Controller()
export class TestController {
  @Get('/users')
  getAllUsers(@QueryParams() query: GetAllUsersInput) {
    return query
  }
}

createKoaServer({
  routePrefix: '/api',
  controllers: [TestController],
  cors: true,
}).listen(3000);
```

### Expected behavior
It should parse and validate data properly like described in the doc.

### Actual behavior
Curl Result
```
shakai-backend|⇒ curl "localhost:3000/api/users?name=alexis"     
TypeError: Cannot read property 'prototype' of undefined
    at ActionParameterHandler.<anonymous> (/home/alexis/dev/shakai/src/ActionParameterHandler.ts:117:111)
    at step (/home/alexis/dev/shakai/shakai-backend/node_modules/routing-controllers/ActionParameterHandler.js:44:23)
    at Object.next (/home/alexis/dev/shakai/shakai-backend/node_modules/routing-controllers/ActionParameterHandler.js:25:53)
    at /home/alexis/dev/shakai/shakai-backend/node_modules/routing-controllers/ActionParameterHandler.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/home/alexis/dev/shakai/shakai-backend/node_modules/routing-controllers/ActionParameterHandler.js:15:12)
    at /home/alexis/dev/shakai/src/ActionParameterHandler.ts:114:63
    at Array.map (<anonymous>)
    at ActionParameterHandler.<anonymous> (/home/alexis/dev/shakai/src/ActionParameterHandler.ts:114:50)
    at step (/home/alexis/dev/shakai/shakai-backend/node_modules/routing-controllers/ActionParameterHandler.js:44:23)% 
```

Versions:
```json
{
  "name": "shakai-backend",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start:dev": "nodemon"
  },
  "devDependencies": {
    "@types/koa": "^2.13.1",
    "@types/koa-bodyparser": "^4.3.0",
    "@types/koa-router": "^7.4.1",
    "@types/node": "^14.14.33",
    "nodemon": "^2.0.7",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.3"
  },
  "dependencies": {
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "kcors": "^2.2.2",
    "koa": "^2.13.1",
    "koa-bodyparser": "^4.3.0",
    "koa-multer": "^1.0.2",
    "koa-router": "^10.0.0",
    "reflect-metadata": "^0.1.13",
    "routing-controllers": "0.8.1"
  }
}
```

```
shakai-backend|⇒ node --version
v14.15.4

shakai-backend|⇒ npm --version
6.14.10
```

Thank you for reading.

**Comment by alexisvisco** [comment]
It did not works with express too, maybe an error related to the project configuration?

**Comment by alexisvisco** [comment]
I created an archive with my minimal repository with the error. Just run yarn install and yarn start:dev 

https://we.tl/t-9Qr6uZUWaH

I didn't find a solution...

**Comment by alexisvisco** [comment]
It was because reflect metadata wasn't imported first. . .
