### ISSUE TITLE
fix: Still throwing "Cannot set headers after they're sent". 

### ISSUE THREAD

**Issue by vatsalkgor** [typestack/routing-controllers#711]
### Description
I've read issue #491 and PR #568 but I'm still facing the same problem. 
I'm adding my repo for reproduction of the bug. Any help would be appreciated. 

**Github Link for the repo**
[https://github.com/vatsalkgor/baps-nz-registration](https://github.com/vatsalkgor/baps-nz-registration
)
### Expected behavior
Should not have any errors shown in the console. 
### Actual behavior
Currently showing 
```
Error [ERR_HTTP_HEADERS_SENT] [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:533:11)
    at ServerResponse.header (/Users/vatsal/DevelopmentProjects/baps-registration/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/vatsal/DevelopmentProjects/baps-registration/node_modules/express/lib/response.js:170:12)
    at /Users/vatsal/DevelopmentProjects/baps-registration/node_modules/swagger-ui-express/index.js:187:11
    at Layer.handle [as handle_request] (/Users/vatsal/DevelopmentProjects/baps-registration/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/vatsal/DevelopmentProjects/baps-registration/node_modules/express/lib/router/index.js:317:13)
    at /Users/vatsal/DevelopmentProjects/baps-registration/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/vatsal/DevelopmentProjects/baps-registration/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/vatsal/DevelopmentProjects/baps-registration/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/Users/vatsal/DevelopmentProjects/baps-registration/node_modules/serve-static/index.js:75:16)
```

**Comment by vatsalkgor** [comment]
Fixed as when adding swaggerUI, the route was called twice.
