### ISSUE TITLE
question: How to add useContainer before imports

### ISSUE THREAD

**Issue by apgapg** [typestack/routing-controllers#718]
I was implementing typedi to inject services hence placing this line
```
// its important to set container before any operation you do with routing-controllers,
// including importing controllers
useContainer(Container);
```
but as per docs it must be placed even before importing controllers, but it seems i am unable to add it before imports. Its continuosly throwing following error
```
    throw new ServiceNotFoundError(identifier);
          ^
ServiceNotFoundError: Service with "MaybeConstructable<ErrorMiddleware>" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.
    at ContainerInstance.get (/Users/ayushpgupta/WebProjects/express-routing-controllers-demo/node_modules/src/container-instance.class.ts:75:11)
    at Function.get (/Users/ayushpgupta/WebProjects/express-routing-controllers-demo/node_modules/src/container.class.ts:61:32)
    at Object.getFromContainer (/Users/ayushpgupta/WebProjects/express-routing-controllers-demo/node_modules/src/container.ts:66:38)
    at MiddlewareMetadata.get instance [as instance] (/Users/ayushpgupta/WebProjects/express-routing-controllers-demo/node_modules/src/metadata/MiddlewareMetadata.ts:54:12)
```

Is there any way to use it before import?

**Comment by NoNameProvided** [comment]
Yes, not just this part but the entire docs should be revamped. The documentation should get some love for all Typestack projects.
