### ISSUE TITLE
[bug] throw error while validate Generic fields

### ISSUE THREAD

**Issue by TechQuery** [typestack/routing-controllers#748]
## My case

Request `GET /?sortBy=name` with codes blow:

```typescript
import { IsString, IsOptional } from 'class-validator';
import { JsonController, Get, QueryParams } from 'routing-controllers';

class BaseModel {
  @IsString()
  name: string;
}

class BaseQuery<T extends BaseModel = BaseModel> {
  @IsString()
  @IsOptional()
  sortBy?: keyof T;
}

@JsonController('/')
export class Controller {
  @Get()
  async getList(@QueryParams() { sortBy = 'name' }: BaseQuery) {
    // your query logic
  }
}
```

## Expected behavior

Code hint with TypeScript generic, and validate parameters as string with routing-controllers.

## Actual behavior

Throw a `ParameterParseJsonError` with this `message`:

> Given parameter sortBy is invalid. Value ("name") cannot be parsed into JSON.

and this `stack`:

    Error: 
        at new HttpError (/node_modules/src/http-error/HttpError.ts:16:18)
        at new BadRequestError (/node_modules/src/http-error/BadRequestError.ts:10:5)
        at new ParameterParseJsonError (/node_modules/src/error/ParameterParseJsonError.ts:10:5)
        at ActionParameterHandler.parseValue (/node_modules/src/ActionParameterHandler.ts:194:15)
        at ActionParameterHandler.normalizeParamValue (/node_modules/src/ActionParameterHandler.ts:139:20)
        at /node_modules/src/ActionParameterHandler.ts:115:39
        at Array.map (<anonymous>)
        at ActionParameterHandler.normalizeParamValue (/node_modules/src/ActionParameterHandler.ts:105:28)
        at ActionParameterHandler.handle (/node_modules/src/ActionParameterHandler.ts:39:24)
        at /node_modules/src/RoutingControllers.ts:114:43

## Possible solution

We may check the **Metadata of Validation decorators** here, to choose a reasonable parser:

https://github.com/typestack/routing-controllers/blob/af0cdf83c070bbc9f1018c09c08c65bdf09fcf64/src/ActionParameterHandler.ts#L138-L142

**Comment by VersusF** [comment]
Linked issue: #527
