### ISSUE TITLE
question: ERR_HTTP_INVALID_STATUS_CODE error while i implement my custom error handler

### ISSUE THREAD

**Issue by kasir-barati** [typestack/routing-controllers#764]
**I was trying to throw new HttpError**
Just throw `HttpError`:
`throw new HttpError(400, 'phoneNumber_already_taken'.toUpperCase());`

**The problem:**
When i send a request to the server I got this error: 
```cmd
undefined Right-hand side of 'instanceof' is not an object
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse.writeHead (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/on-headers/index.js:44:26)
    at ServerResponse.writeHead (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at write_ (_http_outgoing.js:711:9)
    at ServerResponse.end (_http_outgoing.js:825:5)
    at ServerResponse.end (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express-session/index.js:359:19)
    at ServerResponse.send (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/response.js:158:21)
    at errorHandler (/home/kasir/Salam-Sakhteman/infiniti-platform-server/src/middlewares/error.js:43:28)
    at Layer.handle_error (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/index.js:315:13)
    at /home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/layer.js:73:5)
    at trim_prefix (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/index.js:315:13)
    at /home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/home/kasir/Salam-Sakhteman/infiniti-platform-server/node_modules/express/lib/router/layer.js:73:5)
```

And this is my custom error handler: 
```ts
@Middleware({ type: 'after' })
export class CustomErrorHandler implements ExpressErrorMiddlewareInterface {
    error(
        error: HttpError | ValidationError | UnauthorizedError,
        response: expressResponse,
    ): void {
        logger.error('http error occurred', {
            meta: {
                ...serializeError(error),
            },
        });
        if (error instanceof HttpError) {
            response
                .status(error.httpCode)
                .json(new Response<null>(false, null, error.message));
        } else if (error instanceof ValidationError) {
            response
                .status(400)
                .json(new Response(false, { errors: error.constraints }));
        } else if (error instanceof UnauthorizedError) {
            response
                .status(401)
                .json(new Response<null>(false, null, 'unauthorized'));
        } else {
            response
                .status(500)
                .json(new Response(false, {}, 'INTERNAL_SERVER_ERROR'));
        }
    }
}
```

IDK why I get this kind of error. 

My node version: 14.17.4
My routing-controllers version: 0.9.0

**Comment by attilaorosz** [comment]
@kasir-barati Is this still relevant? Your implementation looks incorrect as stated by @angelxmoreno. Could you please try to implement it correctly and circle back?

**Comment by attilaorosz** [comment]
Closing as stale.

**Comment by kasir-barati** [comment]
> @kasir-barati Is this still relevant? Your implementation looks incorrect as stated by @angelxmoreno. Could you please try to implement it correctly and circle back?

Thanks
I fix the issue
It was my wrong implementation.
