### ISSUE TITLE
fix: custom errors extending HttpError class

### ISSUE THREAD

**Issue by willduarte** [typestack/routing-controllers#770]
### Description
I'm trying to create a custom error for Conflict status (409) following the documentation and I'm getting an unexpected result.

**Minimal code-snippet showcasing the problem**

```ts
// my custom error
import { HttpError } from "routing-controllers";

export class ConflictError extends HttpError {
  constructor(message?: string) {
    super(409, message);
  }
}
```

```ts
// controller
import { Param, Delete, JsonController, HttpError } from "routing-controllers";
import { ConflictError } from "../errors/ConflictError";

@JsonController("/samples")
export class SampleController {
  @Delete("/:id")
  remove(@Param("id") id: string) {
    // throw new HttpError(409, "Conflicting when delete"); // 👍🏼 
    throw new ConflictError("Conflict when delete"); // 👎🏼 
  }
}

```

```ts
// app entrypoint
import "reflect-metadata";
import path from "path";
import { createExpressServer } from "routing-controllers";

const app = createExpressServer({
  routePrefix: "/api",
  controllers: [path.join(__dirname, "/controllers/**/*.ts")]
});

app.listen(3000);
```

### Expected behavior

```json
{
  "name": "HttpError",
  "message": "Conflicting when delete",
  "stack": "Error: \n    at new HttpError (/project-path/node_modules/src/http-error/HttpError.ts:16:18)\n    at SampleController.remove (/project-path/src/controllers/SampleController.ts:8:11)\n    at ActionMetadata.callMethod (/project-path/node_modules/src/metadata/ActionMetadata.ts:252:44)\n    at /project-path/node_modules/src/RoutingControllers.ts:123:28\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```

### Actual behavior

```json
{
  "name": "TypeError",
  "message": "Class constructor HttpError cannot be invoked without 'new'",
  "stack": "TypeError: Class constructor HttpError cannot be invoked without 'new'\n    at new ConflictError (/project-path/src/errors/ConflictError.ts:5:5)\n    at SampleController.remove (/project-path/src/controllers/SampleController.ts:9:11)\n    at ActionMetadata.callMethod (/project-path/node_modules/src/metadata/ActionMetadata.ts:252:44)\n    at /project-path/node_modules/src/RoutingControllers.ts:123:28\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```

Packages

```json
...
"devDependencies": {
    "@types/body-parser": "^1.19.1",
    "@types/express": "^4.17.13",
    "@types/multer": "^1.4.7",
    "@types/node": "^16.7.10",
    "@types/uuid": "^8.3.1",
    "ts-node-dev": "^1.1.8",
    "typescript": "^3.9.10"
  },
  "dependencies": {
    "body-parser": "^1.19.0",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",
    "express": "^4.17.1",
    "multer": "^1.4.3",
    "reflect-metadata": "^0.1.13",
    "routing-controllers": "^0.9.0",
    "uuid": "^8.3.2"
  }
...
```

**Comment by attilaorosz** [comment]
@willduarte I literally copy pasted your code and this is the error for me:

```json
{
    "name": "HttpError",
    "message": "Conflict when delete",
    "stack": "Error\n    at new HttpError (E:\\routing-controllers\\src\\http-error\\HttpError.ts:16:18)\n    at new ConflictError (E:\\routing-controllers-repro\\index.ts:16:9)\n    at Cnt.<anonymous> (E:\\routing-controllers-repro\\index.ts:24:15)\n    at Generator.next (<anonymous>)\n    at E:\\routing-controllers-repro\\index.ts:18:71\n    at new Promise (<anonymous>)\n    at __awaiter (E:\\routing-controllers-repro\\index.ts:14:12)\n    at Cnt.route (E:\\routing-controllers-repro\\index.ts:30:16)\n    at ActionMetadata.callMethod (E:\\routing-controllers\\src\\metadata\\ActionMetadata.ts:252:44)\n    at E:\\routing-controllers\\src\\RoutingControllers.ts:123:28"
}
```

According to your error it is missing a `new` keyword somewhere but it present in your example. Could you provide a bit more info?

**Comment by vs4vijay** [comment]
Same error is coming for me too, I am trying to create a new error by extending "HttpError" from routing controllers, and getting this error:
```
TypeError: Class constructor HttpError cannot be invoked without 'new'
```

**Comment by attilaorosz** [comment]
@vs4vijay could you create a repro repo or share what you are trying in a bit more detail?

**Comment by attilaorosz** [comment]
@vs4vijay ok I think I found the source of the problem. Your target is probably ES5, which does not allow extending native classes. Could you try ES6 or higher?

**Comment by attilaorosz** [comment]
Closing as stale.
