### ISSUE TITLE
fix: HttpError on using ctx.redirect

### ISSUE THREAD

**Issue by aj-odev** [typestack/routing-controllers#874]
### Description
When using `ctx.redirect()` to redirect to another site get the Error (HttpError) below.
```
Error 
at new HttpError (/.../.../.../redir/node_modules/src/http-error/HttpError.ts:16:18) 
at new NotFoundError (/.../.../.../redir/node_modules/src/http-error/NotFoundError.ts:10:5) 
at KoaDriver.handleSuccess (/.../.../.../redir/node_modules/src/driver/koa/KoaDriver.ts:257:15) 
at /.../.../.../redir/node_modules/src/RoutingControllers.ts:164:35 
at processTicksAndRejections (node:internal/process/task_queues:96:5) 
at async bodyParser (/.../.../.../redir/node_modules/koa-bodyparser/index.js:82:48) 
at async bodyParser (/.../.../.../redir/node_modules/koa-bodyparser/index.js:95:5)
```

### Code to reproduce

To run the code below use `npm run dev`
Once the server is up and running navigate the browser. Open site `http://localhost:3002/testredirect`. You will see the error above. 
This is probably a bug. (Or am I doing something wrong?)

My code is as follows:
file: package.json =>
```json
{
  "name": "redir",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "ts-node src/app.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@koa/multer": "^3.0.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "koa": "^2.13.4",
    "koa-bodyparser": "^4.3.0",
    "koa-router": "^10.1.1",
    "reflect-metadata": "^0.1.13",
    "routing-controllers": "^0.9.0"
  },
  "devDependencies": {
    "@types/koa": "^2.13.4",
    "@types/koa__multer": "^2.0.4",
    "@types/koa-bodyparser": "^4.3.7",
    "@types/koa-router": "^7.4.4",
    "@types/node": "^17.0.25",
    "ts-node": "^10.7.0"
  }
}
```

file: src/app.ts =>
```ts
import 'reflect-metadata';
import Koa from "koa";
import bodyParser from "koa-bodyparser";
import { useKoaServer } from "routing-controllers";
import { RedirTry } from "./redirTry.comtroller";

const app: Koa = new Koa();

// Enable bodyParser with default options
app.use(bodyParser());

// app.use(async (ctx, next) => {
//     ctx.redirect("https://www.google.com")
// })

useKoaServer(app, {
    controllers: [
        RedirTry
    ]
});

app.listen(3002, () => {
    console.log(`Server running on port 3002`);
});
```

file: src/RedirTry.comtroller.ts =>
```ts
import { Context } from "koa";
import { Controller, Ctx, Get } from "routing-controllers";

@Controller()
export class RedirTry {
    @Get("/testredirect")
    testRedirect(@Ctx() ctx: Context) {
        return ctx.redirect("https://www.google.com");
    }

}
```

### Expected behavior
Should redirect to google as the ctx.redirect() method call in the controller.

### Actual behavior
I see the following error in the browser. (formated for brievity)
```
Error 
at new HttpError (/.../.../.../redir/node_modules/src/http-error/HttpError.ts:16:18) 
at new NotFoundError (/.../.../.../redir/node_modules/src/http-error/NotFoundError.ts:10:5) 
at KoaDriver.handleSuccess (/.../.../.../redir/node_modules/src/driver/koa/KoaDriver.ts:257:15) 
at /.../.../.../redir/node_modules/src/RoutingControllers.ts:164:35 
at processTicksAndRejections (node:internal/process/task_queues:96:5) 
at async bodyParser (/.../.../.../redir/node_modules/koa-bodyparser/index.js:82:48) 
at async bodyParser (/.../.../.../redir/node_modules/koa-bodyparser/index.js:95:5)
```

**Comment by aj-odev** [comment]
Sorry. It is not the issue.
Found the answer using [this link](https://github.com/typestack/routing-controllers/issues/358#issuecomment-360118675). I did not return response.
